SCRUM-11, SCRUM-13, SCRUM-20 Cambios a vista docente
Team-Esquizos/EsquizosP2 pull request #42
Opened 2024-11-16 23:18 UTC by Xhia-x

Se modificó el dropdown del perfil para que aparezca el nombre ahí, además de modificar algunas partes del mismo, ahora cierra sesión el dropdown, en la parte izquierda de la navbar dice si es docente o administrador y las funciones aparecen dependiendo si es admin o docente, además se quitó la animación de las tarjetas de los módulos, estas recogen los datos que están en la bd, como el titulo, su sección y el área al que pertenecen, también se trató de mejor el diseño las mismas.

2024-11-16 23:57 UTC, Yankito requested changes
Por favor indica si esta correcto eliminar la información cada módulo en el componente

2024-11-16 23:57 UTC, Yankito commented on frontend-xquizos/src/components/modulos.vue
> -        <router-link to="/alumnos"> <span class="see-more">Entrar</span></router-link>
Está bien eliminar esta sección en el módulo?

2024-11-17 00:15 UTC, Xhia-x commented on frontend-xquizos/src/components/modulos.vue
> -        <router-link to="/alumnos"> <span class="see-more">Entrar</span></router-link>
Esta bien eliminar eso, era elemento basura que no se ocupaba

2024-11-17 00:29 UTC, Yankito approved these changes

2024-11-17 00:32 UTC, Yankito approved these changes

2024-11-17 00:32 UTC, merged